import {
  renderAdminHeader,
  renderAdminHeaderStyles,
  renderAdminHeaderScript,
} from "./admin-header";
import { escape } from "./broadcasts";

export function renderInboxPage(csrf: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="${escape(csrf)}"><title>Inbox · Pack 170 CMS</title><style>
:root{--deep:#173650;--gold:#f5c542}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;font:16px/1.5 system-ui;color:var(--deep);background:#f3f6f8}main{max-width:1200px;margin:2rem auto;padding:0 1rem}h1,h2{line-height:1.2}a{color:#175b8c}section{background:white;padding:1.5rem;border:1px solid #ced9e1;border-radius:8px;margin:1rem 0}.filters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem}label{display:block;font-weight:600}input,select,button{font:inherit;padding:.6rem;border-radius:5px}input,select{width:100%;border:1px solid #8195a6}button{background:var(--deep);color:white;border:0;cursor:pointer;min-height:44px}button:disabled{opacity:.5;cursor:default}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;text-align:left}th,td{padding:.7rem;border-bottom:1px solid #ddd;vertical-align:top}td{overflow-wrap:anywhere}td:first-child{min-width:180px}pre{font:inherit;white-space:pre-wrap;overflow-wrap:anywhere}#notice{background:#fff3bd;padding:1rem}#notice:empty{display:none}.pager{display:flex;align-items:center;gap:1rem;margin:1rem 0}dl{display:grid;grid-template-columns:6rem 1fr;gap:.5rem}dd{margin:0;overflow-wrap:anywhere}.detail-actions{display:flex;gap:1rem;align-items:end;flex-wrap:wrap}.detail-actions label{max-width:240px}@media(max-width:800px){.filters{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:480px){.filters{grid-template-columns:1fr}section{padding:1rem}}${renderAdminHeaderStyles()}</style></head><body>${renderAdminHeader("inbox")}<main><h1 id="heading">Incoming email</h1><p>Mail sent to any @macon170.com address. Review messages and attachments here.</p><p id="notice" role="status" aria-live="polite"></p><section id="contact" hidden><h2 id="contact-name"></h2><p id="contact-info"></p><a href="/admin/broadcasts">Manage contacts and mailing lists</a> · <a href="/admin/inbox">All incoming email</a></section><section><form id="filters" class="filters">
<label>Search subject or sender<input name="q" type="search" maxlength="200"></label><label>Status<select name="status"><option value="">All statuses</option><option value="new">New</option><option value="reviewed">Reviewed</option><option value="archived">Archived</option><option value="spam">Spam</option></select></label><label>From address<input name="sender" type="email"></label><label>Inbox address<input name="recipient" type="email" placeholder="contact@macon170.com"></label><label>Received from<input name="after" type="date"></label><label>Received before<input name="before" type="date"></label><label>Sort by<select name="sort"><option value="received_at">Received date</option><option value="sender">Sender</option><option value="subject">Subject</option><option value="recipient">Inbox address</option></select></label><label>Order<select name="direction"><option value="desc">Descending</option><option value="asc">Ascending</option></select></label><button>Apply filters</button><button id="reset" type="button">Reset filters</button></form></section><section><div class="table-wrap"><table><thead><tr><th scope="col">Message</th><th scope="col">From / Contact</th><th scope="col">To</th><th scope="col">Received</th><th scope="col">Status</th><th scope="col">Files</th></tr></thead><tbody id="emails"></tbody></table></div><p id="empty" hidden>No incoming emails match these filters.</p><div class="pager"><button id="previous">Previous</button><span id="page"></span><button id="next">Next</button></div></section><section id="detail" hidden tabindex="-1"><button id="close">Close message</button><h2 id="subject"></h2><dl id="metadata"></dl><p id="sender-contact"></p><pre id="body"></pre><h3>Attachments</h3><ul id="attachments"></ul><div class="detail-actions"><label>Review status<select id="status"><option value="new">New</option><option value="reviewed">Reviewed</option><option value="archived">Archived</option><option value="spam">Spam</option></select></label><button id="save-status">Save status</button></div></section></main><script>
${renderAdminHeaderScript()}
const $=id=>document.getElementById(id), form=$('filters'), params=new URLSearchParams(location.search);
let page=Number(params.get('page')||1), current=null, requestVersion=0;
const contactId=params.get('contactId');
for(const el of form.elements) if(el.name && params.has(el.name)) el.value=params.get(el.name);
function node(tag,text){const el=document.createElement(tag);el.textContent=text;return el;}
function notice(text){$('notice').textContent=text;}
function contactLink(id,text){const a=node('a',text);a.href='/admin/inbox?contactId='+encodeURIComponent(id);return a;}
async function api(path,body){const r=await fetch('/api/inbox/v1'+path,{method:body?'PATCH':'GET',headers:{'Content-Type':'application/json','X-CSRF-Token':document.querySelector('meta[name="csrf-token"]').content},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw new Error(data.message||'Request failed.');return data;}
async function load(){const version=++requestVersion;const q=new URLSearchParams(new FormData(form));if(contactId)q.set('contactId',contactId);q.set('page',page);history.replaceState(null,'','?'+q);for(const key of ['after','before'])if(q.get(key))q.set(key,new Date(q.get(key)+'T00:00:00').toISOString());$('previous').disabled=true;$('next').disabled=true;try{const data=await api('?'+q);if(version!==requestVersion)return;$('emails').replaceChildren();for(const e of data.emails){const tr=document.createElement('tr'),subject=node('td',''),open=node('button',e.subject||'(No subject)');open.onclick=()=>show(e.id);subject.append(open);const sender=node('td',e.sender_name?e.sender_name+' <'+e.sender+'>':e.sender);if(e.contact_id){sender.append(document.createElement('br'),contactLink(e.contact_id,e.contact_name||e.sender));}tr.append(subject,sender,node('td',e.recipient),node('td',new Date(e.received_at).toLocaleString()),node('td',e.status),node('td',String(e.attachment_count)));$('emails').append(tr);}$('empty').hidden=data.emails.length>0;$('page').textContent='Page '+page;$('previous').disabled=page<=1;$('next').disabled=!data.hasMore;if(contactId){$('contact').hidden=false;$('heading').textContent='Contact email history';$('contact-name').textContent=data.contact?.name||data.contact?.email||'Contact unavailable';$('contact-info').textContent=data.contact?data.contact.email+' · '+(data.contact.tag||'Active'): 'This contact record could not be found.';}}catch(e){notice(e.message);}}
async function show(id){try{const data=await api('/'+id);current=data.email;$('subject').textContent=current.subject||'(No subject)';$('metadata').replaceChildren();for(const [label,value] of [['From',current.sender],['Inbox',current.recipient],['To',data.content.to],['Cc',data.content.cc],['Bcc',data.content.bcc],['Reply to',data.content.replyTo],['Sent',current.sent_at],['Received',new Date(current.received_at).toLocaleString()]]){if(value)$('metadata').append(node('dt',label),node('dd',value));}$('sender-contact').replaceChildren();if(current.contact_id)$('sender-contact').append(contactLink(current.contact_id,'View '+(current.contact_name||current.sender)+' and their email history'));$('body').textContent=data.content.text||'(Empty message)';$('attachments').replaceChildren();for(const a of data.content.attachments){const li=node('li',''),link=node('a',a.name+' ('+Math.ceil(a.size/1024)+' KB)');link.href=a.download;link.setAttribute('download','');li.append(link);$('attachments').append(li);}if(!data.content.attachments.length)$('attachments').append(node('li','No attachments'));$('status').value=current.status;$('detail').hidden=false;$('detail').focus();$('detail').scrollIntoView({behavior:'smooth'});}catch(e){notice(e.message);}}
form.onsubmit=e=>{e.preventDefault();page=1;notice('');load();};$('reset').onclick=()=>{form.reset();page=1;load();};$('previous').onclick=()=>{page--;load();};$('next').onclick=()=>{page++;load();};$('close').onclick=()=>{$('detail').hidden=true;current=null;};$('save-status').onclick=async()=>{if(!current)return;const id=current.id;$('save-status').disabled=true;try{await api('/'+id,{status:$('status').value,expectedRevision:current.revision});notice('Status saved.');await load();await show(id);}catch(e){notice(e.message);}finally{$('save-status').disabled=false;}};load();
</script></body></html>`;
}
