import {
  renderAdminHeader,
  renderAdminHeaderScript,
  renderAdminHeaderStyles,
} from "./admin-header";

export function renderInvitePage(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>Invite a volunteer | Pack 170 CMS</title><style>
:root{color-scheme:light;--blue:#003f87;--deep:#002b5c;--gold:#fcd116;--ink:#272b2e;--muted:#5d6670;--paper:#fffdf5;--rule:#ccd6e0;--green:#1f6b45;--red:#9b2c2c}*{box-sizing:border-box}body{margin:0;background:#f8f7f2;color:var(--ink);font:16px/1.5 system-ui,sans-serif}a{color:var(--blue)}.skip{position:absolute;left:-9999px}.skip:focus{left:1rem;top:1rem;background:#fff;padding:.75rem;z-index:10}${renderAdminHeaderStyles()}main{max-width:760px;margin:auto;padding:clamp(1.5rem,4vw,3rem)}h1{font-size:clamp(2rem,5vw,3rem);line-height:1.1;margin:0 0 .65rem}.intro{color:var(--muted);margin:0 0 2rem;max-width:62ch}.card{background:var(--paper);border:1px solid var(--rule);border-radius:8px 22px 12px 8px;padding:clamp(1.25rem,3vw,2rem);box-shadow:6px 8px 0 rgba(0,43,92,.08)}form{display:grid;gap:1.25rem}label{display:grid;font-weight:700;gap:.45rem}input,select,button{font:inherit}input,select{background:white;border:1px solid var(--rule);border-radius:6px;min-height:2.8rem;padding:.6rem .7rem}button{background:var(--blue);border:0;border-radius:6px 12px 8px 6px;color:white;cursor:pointer;font-weight:800;min-height:3rem;padding:.75rem 1rem}button:hover{background:var(--deep)}button:disabled{cursor:progress;opacity:.7}.notice{border-inline-start:4px solid;margin:1.25rem 0 0;padding:.8rem 1rem}.notice--success{background:#e8f4ec;border-color:var(--green);color:#164b30}.notice--error{background:#fbe9e7;border-color:var(--red);color:#6f251f}.help{color:var(--muted);font-size:.92rem;margin:1.5rem 0 0}input:focus-visible,select:focus-visible,button:focus-visible,a:focus-visible{box-shadow:0 0 0 4px var(--gold);outline:3px solid var(--deep);outline-offset:1px}@media(max-width:640px){main{padding:1.25rem}.card{padding:1.25rem}}
</style></head><body><a class="skip" href="#main">Skip to invitation form</a>${renderAdminHeader("dash")}<main id="main"><h1>Invite a volunteer</h1><p class="intro">Send a one-time setup link. The volunteer chooses their own password and receives only the role selected below.</p><section class="card" aria-labelledby="invite-form-title"><h2 id="invite-form-title">Volunteer details</h2><form id="invite-form" action="/admin/invite-user" method="post"><label for="first-name">First name<input id="first-name" name="first_name" autocomplete="given-name" required></label><label for="last-name">Last name<input id="last-name" name="last_name" autocomplete="family-name" required></label><label for="email">Email address<input id="email" name="email" type="email" autocomplete="email" required></label><label for="role">CMS role<select id="role" name="role" required><option value="viewer">Viewer — view content</option><option value="author">Author — draft content</option><option value="editor">Editor — manage content</option><option value="admin">Administrator — full CMS access</option></select></label><button type="submit">Send invitation</button></form><div id="feedback" aria-live="polite"></div></section><p class="help">Invitation links expire after seven days. Never share an invitation link outside its intended recipient.</p></main><script>
${renderAdminHeaderScript()}
const form=document.querySelector('#invite-form');const feedback=document.querySelector('#feedback');const button=form.querySelector('button');form.addEventListener('submit',async(event)=>{event.preventDefault();button.disabled=true;button.textContent='Sending…';feedback.replaceChildren();try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),credentials:'same-origin'});const data=await response.json();const notice=document.createElement('p');notice.className='notice '+(response.ok?'notice--success':'notice--error');notice.setAttribute('role',response.ok?'status':'alert');notice.textContent=data.message||data.error||'Unable to send the invitation.';feedback.append(notice);if(response.ok)form.reset()}catch{const notice=document.createElement('p');notice.className='notice notice--error';notice.setAttribute('role','alert');notice.textContent='Unable to send the invitation. Check your connection and try again.';feedback.append(notice)}finally{button.disabled=false;button.textContent='Send invitation'}});
</script></body></html>`;
}
